# Generated by Django 2.0.7 on 2018-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('color_pattern', models.CharField(max_length=128)),
                ('favourite_prey', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('venomous', models.BooleanField(default=True)),
            ],
        ),
    ]
